name: kew
adopt-info: kew
summary: Listen to music in the terminal.
description: |
  Listen to music in the terminal.
    
license: GPL-2.0

base: core24
grade: stable 
confinement: strict
compression: lzo


apps:
  kew:
    command: usr/bin/kew
    plugs:
      - home
      - audio-playack
      - x11
      
parts:
  kew:
    source: https://github.com/ravachol/kew
    source-type: git
    plugin: nil
    override-build: |
      bash -c "curl https://raw.githubusercontent.com/ravachol/kew/main/install.sh | bash"

    build-packages:
      - sudo
      
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"       
